/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import Connect.Connect;

/**
 *
 * @author Mohamed
 */
public class add_teach extends javax.swing.JPanel {

    /**
     * Creates new form manage_teach
     */
    public add_teach() {
        initComponents();
        Connect.Teacher(teacher);
        id.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        teacher = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        quali = new javax.swing.JComboBox<>();
        special = new javax.swing.JComboBox<>();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        salary = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        teacher.setAutoCreateRowSorter(true);
        teacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Phone", "Age", "Qualification", "specialization", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        teacher.setRowHeight(20);
        teacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(teacher);
        if (teacher.getColumnModel().getColumnCount() > 0) {
            teacher.getColumnModel().getColumn(0).setResizable(false);
            teacher.getColumnModel().getColumn(1).setResizable(false);
            teacher.getColumnModel().getColumn(2).setResizable(false);
            teacher.getColumnModel().getColumn(3).setResizable(false);
            teacher.getColumnModel().getColumn(4).setResizable(false);
            teacher.getColumnModel().getColumn(5).setResizable(false);
            teacher.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Modifiy"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quali.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Qualification", "Matriculation", "Diploma", "Magiser", " " }));
        quali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qualiActionPerformed(evt);
            }
        });
        jPanel1.add(quali, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 110, 28));

        special.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Specialization", "Islamic", "Math", "Arabic", "English", "Technology", "Engineering", "business", " " }));
        special.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialActionPerformed(evt);
            }
        });
        jPanel1.add(special, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 110, 28));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 240, 28));
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 225, 28));
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 220, 28));
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 83, 28));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Age");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 84, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Address");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 84, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Phone");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 84, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 24, 84, 20));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 90, 30));
        jPanel1.add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 80, 28));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Salary");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 84, -1));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 90, 30));

        id.setEditable(false);
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 40, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/icons8-teacher-34.png"))); // NOI18N
        jLabel11.setText("Teachers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel11))
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)))
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void specialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Connect.insert_teacher(teacher, name, address, phone, age, special, quali, salary);
        name.setText("");
        address.setText("");
        phone.setText("");
        age.setText("");
        salary.setText("");
        special.setSelectedIndex(0);
        quali.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void teacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherMouseClicked
        Connect.get_teacher(teacher, name, address, phone, age, special, quali, salary, id);
    }//GEN-LAST:event_teacherMouseClicked

    private void qualiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qualiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qualiActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        name.setText("");
        address.setText("");
        phone.setText("");
        age.setText("");
        salary.setText("");
        special.setSelectedIndex(0);
        quali.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JComboBox<String> quali;
    private javax.swing.JTextField salary;
    private javax.swing.JComboBox<String> special;
    private javax.swing.JTable teacher;
    // End of variables declaration//GEN-END:variables
}
