/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import Connect.Connect;
import javax.swing.plaf.basic.*;

/**
 *
 * @author Mohamed
 */
public class add_std extends javax.swing.JPanel {

    /**
     * Creates new form add_std
     */
    public add_std() {
        initComponents();
        Connect.Std(add_std);
        id.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        add_std = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        clas = new javax.swing.JComboBox<>();
        subject = new javax.swing.JComboBox<>();
        result = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        mark1 = new javax.swing.JTextField();
        mark2 = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        add_std.setAutoCreateRowSorter(true);
        add_std.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Age", "Class", "Subjects", "Marks 1", "Marks 2", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        add_std.setRowHeight(20);
        add_std.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_stdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(add_std);
        if (add_std.getColumnModel().getColumnCount() > 0) {
            add_std.getColumnModel().getColumn(0).setResizable(false);
            add_std.getColumnModel().getColumn(1).setResizable(false);
            add_std.getColumnModel().getColumn(2).setResizable(false);
            add_std.getColumnModel().getColumn(3).setResizable(false);
            add_std.getColumnModel().getColumn(4).setResizable(false);
            add_std.getColumnModel().getColumn(5).setResizable(false);
            add_std.getColumnModel().getColumn(6).setResizable(false);
            add_std.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Modifiy"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class", "A", "B", "C" }));
        clas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasActionPerformed(evt);
            }
        });
        jPanel1.add(clas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 91, 30));

        subject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Subject", "5", "6", "7" }));
        subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectActionPerformed(evt);
            }
        });
        jPanel1.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 99, 30));

        result.setEditable(false);
        result.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                resultKeyReleased(evt);
            }
        });
        jPanel1.add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 72, 30));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 52, 193, 30));
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 51, 170, 30));

        mark1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mark1KeyReleased(evt);
            }
        });
        jPanel1.add(mark1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 52, 30));

        mark2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mark2KeyReleased(evt);
            }
        });
        jPanel1.add(mark2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 52, 30));
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 51, 90, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Age");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 23, 58, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Address");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 23, 94, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Marks2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 85, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Result");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 95, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Marks1");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 85, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, 100, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 100, 30));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 100, 30));

        id.setEditable(false);
        id.setOpaque(false);
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 40, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/icons8-school-girl-36.png"))); // NOI18N
        jLabel3.setText("Students");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectActionPerformed

    private void clasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clasActionPerformed

    private void add_stdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_stdMouseClicked
        Connect.get_std(add_std,id, name, address, age, clas, subject, mark1, mark2, result);
    }//GEN-LAST:event_add_stdMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connect.insert_std(add_std, name, address, age, clas, subject, mark1, mark2, result);
        name.setText("");
        age.setText("");
        address.setText("");
        mark1.setText("");
        mark2.setText("");
        result.setText("");
        clas.setSelectedIndex(0);
        subject.setSelectedIndex(0);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void resultKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resultKeyReleased
        result.setText((Integer.parseInt(mark1.getText()) + Integer.parseInt(mark2.getText())) / 2 + "");
    }//GEN-LAST:event_resultKeyReleased

    private void mark1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mark1KeyReleased
        result.setText((Integer.parseInt(mark1.getText()) + Integer.parseInt(mark2.getText())) / 2 + "");
    }//GEN-LAST:event_mark1KeyReleased

    private void mark2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mark2KeyReleased
        result.setText((Integer.parseInt(mark1.getText()) + Integer.parseInt(mark2.getText())) / 2 + "");
    }//GEN-LAST:event_mark2KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        name.setText("");
        age.setText("");
        address.setText("");
        mark1.setText("");
        mark2.setText("");
        result.setText("");
        clas.setSelectedIndex(0);
        subject.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable add_std;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JComboBox<String> clas;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mark1;
    private javax.swing.JTextField mark2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField result;
    private javax.swing.JComboBox<String> subject;
    // End of variables declaration//GEN-END:variables
}
